services:
  postgres:
    image: postgres:16-alpine
    emvironment:
      POSTGRES_USER: ${DB_USER:-finboss}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-finboss}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  finboss"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER:-finboss}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-finboss}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: